#!/usr/bin/env bash
set -eu
files=$(git diff --name-only --cached --no-ext-diff --diff-filter=d)
if ! [ "$files" ]; then exit 0; fi

GIT_DIR=$(realpath "$(git rev-parse --git-dir)")
export GIT_DIR

# Run local hooks first, since those are more important.
local_hook=$(git rev-parse --git-common-dir)/hooks/$(basename "$0")
if [ -e "$local_hook" ]; then
    # TODO: adopt these hooks to work with the CWD instead?
    "$local_hook"
fi

# Now run global hooks.
tmpdir=$(mktemp -d --tmpdir "$(basename "$(realpath .)")-pre-commit.XXXX")
trap 'rm -r "$tmpdir"' EXIT
printf %s "$files" | tr '\n' '\0' | xargs -0 git checkout-index --prefix="$tmpdir/"
cd "$tmpdir"

for c in symlinks case_conflict end_of_file executables_have_shebangs json merge_conflict shebang_scripts_are_executable toml vcs_permalinks; do
    find . -type f -print0 | xargs -0 python "$(realpath "$(dirname "$0")")"/pre_commit_hooks/check_$c.py
done
