import { expect, mock, test } from "bun:test";
import type { SessionManager as PiSessionManager } from "@earendil-works/pi-coding-agent";
import { existsSync, mkdtempSync, readFileSync, readdirSync, realpathSync, rmSync } from "node:fs";
import { createServer, type Socket } from "node:net";
import { homedir, tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { pathToFileURL } from "node:url";

// Bun ignores NODE_PATH. Load the installed package's public import export, not
// checkout internals or a fake SessionManager, before resolving the extension.
const packageDirs = process.env.PI_PACKAGE_DIR ? [process.env.PI_PACKAGE_DIR] : [
  join(homedir(), ".local/share/pi/node/node_modules/@earendil-works/pi-coding-agent"),
  "/opt/agent-pi/src/packages/coding-agent",
];
const installedDir = packageDirs.find(dir => existsSync(join(dir, "package.json")));
if (!installedDir) throw new Error("Installed Pi SDK not found; set PI_PACKAGE_DIR to its package directory");
const packageDir = realpathSync(installedDir);
const manifest = JSON.parse(readFileSync(join(packageDir, "package.json"), "utf8"));
const publicEntry = manifest.exports?.["."]?.import;
if (manifest.name !== "@earendil-works/pi-coding-agent" || typeof publicEntry !== "string") {
  throw new Error(`Pi package has no supported public import export: ${packageDir}`);
}
const sdk = await import(pathToFileURL(resolve(packageDir, publicEntry)).href);
mock.module("@earendil-works/pi-coding-agent", () => sdk);
const { SessionManager } = sdk;
const { default: sessionSide, publishRestartSession, requestOwner, snapshotSession } = await import("../../../config/pi-agent/pi-extensions/session-side.ts");

const usage = { input: 1, output: 1, cacheRead: 0, cacheWrite: 0, totalTokens: 2,
  cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0, total: 0 } };
const assistant = (calls: string[] = [], stopReason = calls.length ? "toolUse" : "stop") => ({
  role: "assistant", content: calls.length ? calls.map(id => ({ type: "toolCall", id, name: "read", arguments: {} })) : [{ type: "text", text: "finished" }],
  api: "anthropic-messages", provider: "anthropic", model: "fixture", usage, stopReason, timestamp: 1,
} as any);
const result = (id: string) => ({ role: "toolResult", toolCallId: id, toolName: "read",
  content: [{ type: "text", text: id }], isError: false, timestamp: 2 } as any);

function fixture() {
  const dir = mkdtempSync(join(tmpdir(), "pi-side-"));
  return { dir, source: SessionManager.create(dir, dir), cleanup: () => rmSync(dir, { recursive: true, force: true }) };
}

test("snapshot keeps only the active completed branch, compaction, settings and summaries; never mutates source", () => {
  const f = fixture();
  try {
    const sm = f.source;
    sm.appendModelChange("anthropic", "fixture");
    sm.appendThinkingLevelChange("high");
    const user = sm.appendMessage({ role: "user", content: "root", timestamp: 1 });
    sm.appendMessage(assistant());
    const abandoned = sm.appendMessage({ role: "user", content: "abandoned", timestamp: 2 });
    sm.branchWithSummary(user, "abandoned path summary");
    sm.appendMessage(assistant(["a", "b"]));
    sm.appendMessage(result("b"));
    sm.appendMessage(result("a"));
    sm.appendCompaction("compacted history", user, 4000, { files: ["x"] }, true, usage);
    sm.appendCustomEntry("live-worker", { pid: 123, session: "do not copy" });
    sm.appendCustomMessageEntry("context", "durable context", true, { pid: 321 });
    sm.appendMessage({ role: "user", content: "ongoing", timestamp: 3 });
    const finishedLeaf = sm.getLeafId();
    sm.appendMessage(assistant(["c", "d"]));
    sm.appendMessage(result("c"));
    const before = JSON.stringify(sm.getEntries());
    const fileBefore = readFileSync(sm.getSessionFile()!, "utf8");
    const leafBefore = sm.getLeafId();
    const file = snapshotSession(sm as any);
    const copy = SessionManager.open(file);
    expect(copy.getSessionId()).not.toBe(sm.getSessionId());
    expect(copy.getHeader()?.parentSession).toBe(sm.getSessionFile());
    expect(copy.getEntries().some(e => e.id === abandoned)).toBe(false);
    expect(copy.getEntries().some(e => e.type === "custom")).toBe(false);
    expect(copy.getEntries().filter(e => e.type === "message" && e.message.role === "toolResult").length).toBe(2);
    const expected = SessionManager.open(sm.getSessionFile()!);
    expected.branch(finishedLeaf!);
    // New entry ids/timestamps are generated by the public append APIs; custom
    // message details are deliberately omitted because they are extension state.
    const context = (manager: PiSessionManager) => {
      const value = manager.buildSessionContext();
      return { ...value, messages: value.messages.map(({ timestamp, ...message }: any) => {
        const { fromId, details, ...content } = message;
        return content;
      }) };
    };
    expect(context(copy)).toEqual(context(expected));
    expect(copy.getEntries().find(e => e.type === "custom_message")).not.toHaveProperty("details.pid");
    expect(JSON.stringify(sm.getEntries())).toBe(before);
    expect(sm.getLeafId()).toBe(leafBefore);
    expect(readFileSync(sm.getSessionFile()!, "utf8")).toBe(fileBefore);
    expect(snapshotSession(sm as any)).not.toBe(file);
  } finally { f.cleanup(); }
});

test("historical failed assistants do not erase later completed turns", () => {
  const f = fixture();
  try {
    for (const reason of ["error", "aborted", "deferred"]) {
      const source = SessionManager.create(f.dir, f.dir);
      const first = { role: "user", content: "first attempt", timestamp: 1 } as const;
      const failed = assistant([], reason);
      const later = { role: "user", content: "continue after failure", timestamp: 2 } as const;
      const finished = assistant();
      source.appendMessage(first);
      source.appendMessage(failed);
      source.appendMessage(later);
      source.appendMessage(finished);
      // Native context retains terminal failures and the resumed conversation;
      // /split excludes the failed response, not the subsequent completed turns.
      expect(source.buildSessionContext().messages).toEqual([first, failed, later, finished]);
      const entriesBefore = JSON.stringify(source.getEntries());
      const fileBefore = readFileSync(source.getSessionFile()!, "utf8");
      const leafBefore = source.getLeafId();
      const copy = SessionManager.open(snapshotSession(source));
      expect(copy.buildSessionContext().messages).toEqual([first, later, finished]);
      expect(JSON.stringify(source.getEntries())).toBe(entriesBefore);
      expect(readFileSync(source.getSessionFile()!, "utf8")).toBe(fileBefore);
      expect(source.getLeafId()).toBe(leafBefore);
    }
  } finally { f.cleanup(); }
});

test("canceled historical tool batches are removed whole, preserving resumed turns and later compaction", () => {
  const f = fixture();
  try {
    const source = f.source;
    source.appendMessage({ role: "user", content: "canceled attempt", timestamp: 1 });
    source.appendMessage(assistant(["old-a", "old-b"]));
    source.appendMessage(result("old-a"));
    const resumed = source.appendMessage({ role: "user", content: "resumed", timestamp: 2 });
    source.appendMessage(result("old-b")); // A late result must not become orphan context.
    const completedBatch = assistant(["new-a", "new-b"]);
    source.appendMessage(completedBatch);
    source.appendMessage(result("new-b"));
    source.appendMessage(result("new-a"));
    source.appendMessage(assistant());
    source.appendCompaction("summary after recovery", resumed, 1000);
    source.appendMessage({ role: "user", content: "after compaction", timestamp: 3 });
    source.appendMessage(assistant());
    source.appendMessage({ role: "user", content: "still running", timestamp: 4 });
    source.appendMessage(assistant(["tail-a", "tail-b"]));
    source.appendMessage(result("tail-a"));
    const before = JSON.stringify(source.getEntries());
    const fileBefore = readFileSync(source.getSessionFile()!, "utf8");
    const leafBefore = source.getLeafId();
    const copy = SessionManager.open(snapshotSession(source));
    const messages = copy.getEntries().filter((entry: any) => entry.type === "message").map((entry: any) => entry.message);
    expect(messages).toEqual([
      { role: "user", content: "canceled attempt", timestamp: 1 },
      { role: "user", content: "resumed", timestamp: 2 },
      completedBatch, result("new-b"), result("new-a"), assistant(),
      { role: "user", content: "after compaction", timestamp: 3 }, assistant(),
      { role: "user", content: "still running", timestamp: 4 },
    ]);
    const context = copy.buildSessionContext().messages;
    expect(context[0]).toMatchObject({ role: "compactionSummary", summary: "summary after recovery", tokensBefore: 1000 });
    expect(context.slice(1)).toEqual(messages.slice(1));
    expect(JSON.stringify(source.getEntries())).toBe(before);
    expect(readFileSync(source.getSessionFile()!, "utf8")).toBe(fileBefore);
    expect(source.getLeafId()).toBe(leafBefore);
  } finally { f.cleanup(); }
});

test("compaction boundaries advance past omitted state and failed or incomplete responses", () => {
  const f = fixture();
  try {
    for (const omitted of ["custom", "session_info", "error", "aborted", "deferred", "incomplete"]) {
      const source = SessionManager.create(f.dir, f.dir);
      source.appendMessage({ role: "user", content: "already summarized", timestamp: 1 });
      source.appendMessage(assistant());
      let boundary: string;
      if (omitted === "custom") boundary = source.appendCustomEntry("live-worker", { secret: "not context" });
      else if (omitted === "session_info") boundary = source.appendSessionInfo("source title");
      else if (omitted === "incomplete") {
        boundary = source.appendMessage(assistant(["missing", "partial"]));
        source.appendMessage(result("partial"));
      } else boundary = source.appendMessage(assistant([], omitted));
      source.appendCustomEntry("another-worker", { pid: 123 });
      const retained = { role: "user", content: "retained turn", timestamp: 2 } as const;
      source.appendMessage(retained);
      source.appendMessage(assistant());
      source.appendCompaction("first summary", boundary, 1000, { files: ["x"] }, true, usage);
      // Repeated compaction must preserve the same retained range, not older turns.
      source.appendCompaction("latest summary", boundary, 2000, { files: ["y"] }, true, usage);
      const after = { role: "user", content: "after compaction", timestamp: 3 } as const;
      source.appendMessage(after);
      source.appendMessage(assistant());
      const before = readFileSync(source.getSessionFile()!, "utf8");
      const copy = SessionManager.open(snapshotSession(source));
      const context = copy.buildSessionContext().messages;
      expect(context[0]).toMatchObject({ role: "compactionSummary", summary: "latest summary", tokensBefore: 2000 });
      // Pi includes an earlier summary when it lies inside the latest retained range.
      expect(context.slice(1, 3)).toEqual([retained, assistant()]);
      expect(context[3]).toMatchObject({ role: "compactionSummary", summary: "first summary", tokensBefore: 1000 });
      expect(context.slice(4)).toEqual([after, assistant()]);
      expect(copy.getEntries().filter((e: any) => e.type === "compaction").map((e: any) =>
        ({ summary: e.summary, details: e.details, fromHook: e.fromHook, usage: e.usage }))).toEqual([
        { summary: "first summary", details: { files: ["x"] }, fromHook: true, usage },
        { summary: "latest summary", details: { files: ["y"] }, fromHook: true, usage },
      ]);
      expect(copy.getEntries().some((e: any) => e.type === "custom")).toBe(false);
      expect(readFileSync(source.getSessionFile()!, "utf8")).toBe(before);
    }
  } finally { f.cleanup(); }
});

test("an entirely omitted retained range does not resurrect summarized messages", () => {
  const f = fixture();
  try {
    const source = f.source;
    source.appendMessage({ role: "user", content: "already summarized", timestamp: 1 });
    source.appendMessage(assistant());
    const boundary = source.appendCustomEntry("live-worker", { secret: "not context" });
    source.appendMessage(assistant([], "error"));
    source.appendCompaction("only summary remains", boundary, 1000);
    const summaryOnly = SessionManager.open(snapshotSession(source)).buildSessionContext().messages;
    expect(summaryOnly).toHaveLength(1);
    expect(summaryOnly[0]).toMatchObject({ role: "compactionSummary", summary: "only summary remains" });
    const after = { role: "user", content: "after compaction", timestamp: 2 } as const;
    source.appendMessage(after);
    source.appendMessage(assistant());
    const copy = SessionManager.open(snapshotSession(source));
    const messages = copy.buildSessionContext().messages;
    expect(messages[0]).toMatchObject({ role: "compactionSummary", summary: "only summary remains" });
    expect(messages.slice(1)).toEqual([after, assistant()]);
    const compaction = copy.getEntries().find((e: any) => e.type === "compaction");
    expect(copy.getEntry(compaction.firstKeptEntryId)).toBeDefined();
    expect(JSON.stringify(copy.getEntries())).not.toContain("not context");
  } finally { f.cleanup(); }
});

test("a missing source compaction boundary fails without publishing a snapshot", () => {
  const f = fixture();
  try {
    f.source.appendMessage({ role: "user", content: "source", timestamp: 1 });
    f.source.appendMessage(assistant());
    f.source.appendCompaction("invalid boundary", "missing-entry", 1000);
    const filesBefore = readdirSync(f.dir);
    const sourceBefore = readFileSync(f.source.getSessionFile()!, "utf8");
    expect(() => snapshotSession(f.source)).toThrow("retained entry is outside its source range");
    expect(readdirSync(f.dir)).toEqual(filesBefore);
    expect(readFileSync(f.source.getSessionFile()!, "utf8")).toBe(sourceBefore);
  } finally { f.cleanup(); }
});

test("snapshot follows a navigated source leaf rather than the last persisted branch", () => {
  const f = fixture();
  try {
    const root = f.source.appendMessage({ role: "user", content: "root", timestamp: 1 });
    f.source.appendMessage(assistant());
    f.source.appendMessage({ role: "user", content: "inactive", timestamp: 2 });
    f.source.branch(root);
    const fileBefore = readFileSync(f.source.getSessionFile()!, "utf8");
    const copy = SessionManager.open(snapshotSession(f.source as any));
    expect(copy.buildSessionContext().messages).toEqual([{ role: "user", content: "root", timestamp: 1 }]);
    expect(f.source.getLeafId()).toBe(root);
    expect(readFileSync(f.source.getSessionFile()!, "utf8")).toBe(fileBefore);
  } finally { f.cleanup(); }
});

test("empty, pending, failed and deferred snapshots are saved without an unfinished assistant", () => {
  const f = fixture();
  try {
    for (const reason of [undefined, "pending", "error", "aborted", "deferred"]) {
      const sm = SessionManager.create(f.dir, f.dir);
      sm.appendMessage({ role: "user", content: "question", timestamp: 1 });
      if (reason) sm.appendMessage(assistant([], reason));
      const file = snapshotSession(sm as any);
      expect(existsSync(file)).toBe(true);
      expect(SessionManager.open(file).buildSessionContext().messages.map(m => m.role)).toEqual(["user"]);
    }
    const empty = snapshotSession(SessionManager.create(f.dir, f.dir) as any);
    expect(SessionManager.open(empty).getEntries()).toEqual([]);
  } finally { f.cleanup(); }
});

async function controller(dir: string, respond: (request: any, socket: Socket) => void) {
  const path = join(dir, "owner.sock");
  const requests: any[] = [];
  const sockets = new Set<Socket>();
  const server = createServer(socket => {
    sockets.add(socket);
    socket.on("close", () => sockets.delete(socket));
    let buffer = "";
    socket.setEncoding("utf8");
    socket.on("data", chunk => {
      buffer += chunk;
      if (!buffer.includes("\n")) return;
      const request = JSON.parse(buffer.slice(0, buffer.indexOf("\n")));
      requests.push(request);
      respond(request, socket);
    });
  });
  await new Promise<void>(resolve => server.listen(path, resolve));
  return { path, requests, close: async () => {
    for (const socket of sockets) socket.destroy();
    await new Promise<void>(resolve => server.close(() => resolve()));
  } };
}

test("ordinary /split command and readiness use host socket; no source control/editor/prompt methods touched", async () => {
  const f = fixture();
  const oldOwner = process.env.CODEX_SANDBOX_PI_OWNER;
  const oldAttachment = process.env.CODEX_SANDBOX_PI_ATTACHMENT;
  const oldAgentDir = process.env.PI_CODING_AGENT_DIR;
  let ephemeralDir: string | undefined;
  let launchMode = "success";
  const host = await controller(f.dir, (_request, socket) => {
    if (launchMode === "lost-ack") socket.end();
    else socket.end(JSON.stringify(launchMode === "failure" ? { ok: false, error: "pane failed" } : { ok: true, pane: "%9" }) + "\n");
  });
  try {
    delete process.env.CODEX_SANDBOX_PI_OWNER;
    delete process.env.CODEX_SANDBOX_PI_ATTACHMENT;
    sessionSide({ registerCommand: () => { throw Error("disabled"); }, on: () => { throw Error("disabled"); } } as any);
    process.env.CODEX_SANDBOX_PI_OWNER = host.path;
    process.env.CODEX_SANDBOX_PI_ATTACHMENT = "token";
    const commands = new Map<string, any>();
    const events = new Map<string, any>();
    sessionSide({ registerCommand: (name: string, options: any) => commands.set(name, options.handler),
      on: (name: string, handler: any) => events.set(name, handler) } as any);
    expect([...commands.keys()]).toEqual(["split"]);
    expect([...events.keys()]).toEqual(["session_start"]);
    const notifications: string[] = [];
    const forbidden = () => { throw Error("must not touch source runtime/editor"); };
    const ctx = { mode: "tui", sessionManager: f.source, ui: { notify: (s: string) => notifications.push(s),
      setEditorText: forbidden, getEditorText: forbidden }, abort: forbidden, waitForIdle: forbidden,
      newSession: forbidden, fork: forbidden, switchSession: forbidden, isIdle: forbidden };
    await events.get("session_start")({}, ctx);
    expect(host.requests[0]).toEqual({ op: "ready", attachment: "token", session: f.source.getSessionFile() });
    await commands.get("split")("", { ...ctx, mode: "rpc" });
    expect(host.requests.length).toBe(1);
    await commands.get("split")("", ctx);
    const snapshot = host.requests[1].session;
    expect(host.requests[1]).toEqual({ op: "side", attachment: "token", session: snapshot });
    expect(existsSync(snapshot)).toBe(true);
    launchMode = "failure";
    await commands.get("split")("", ctx);
    expect(existsSync(host.requests[2].session)).toBe(false);
    expect(existsSync(snapshot)).toBe(true);
    expect(notifications.at(-1)).toContain("pane failed");
    launchMode = "lost-ack";
    await commands.get("split")("", ctx);
    expect(existsSync(host.requests[3].session)).toBe(true);
    expect(notifications.at(-1)).toContain("launch outcome unknown");
    expect(host.requests.length).toBe(4);
    launchMode = "success";
    const prompt = "--env A=B @file 'quoted'\nsecond line";
    await commands.get("split")(prompt, ctx);
    expect(host.requests.at(-1)).toEqual({ op: "side", attachment: "token",
      session: host.requests.at(-1).session, prompt });
    const sent: string[] = [];
    process.env.CODEX_SANDBOX_PI_SPLIT_PROMPT = prompt;
    sessionSide({ registerCommand: () => {},
      on: (name: string, handler: any) => events.set(name, handler),
      sendUserMessage: (message: string) => sent.push(message) } as any);
    expect(process.env.CODEX_SANDBOX_PI_SPLIT_PROMPT).toBeUndefined();
    await events.get("session_start")({}, ctx);
    await events.get("session_start")({ reason: "reload" }, ctx);
    expect(sent).toEqual([prompt]);
    for (const reason of ["fork", "resume", "new", "reload"]) {
      const source = SessionManager.create(f.dir, join(f.dir, reason));
      await events.get("session_start")({ reason }, { ...ctx, sessionManager: source });
      expect(host.requests.at(-1)).toEqual({ op: "ready", attachment: "token", session: source.getSessionFile() });
      expect(existsSync(source.getSessionFile()!)).toBe(false);
    }
    process.env.PI_CODING_AGENT_DIR = join(f.dir, "agent-dir");
    const ephemeral = SessionManager.inMemory(f.dir);
    ephemeral.appendMessage({ role: "user", content: "ephemeral context", timestamp: 1 });
    const before = JSON.stringify(ephemeral.getEntries());
    ephemeralDir = SessionManager.create(f.dir).getSessionDir();
    await events.get("session_start")({ reason: "new" }, { ...ctx, sessionManager: ephemeral });
    expect(host.requests.at(-1)).toEqual({ op: "ready", attachment: "token", session: null, sessionDir: ephemeralDir });
    await commands.get("split")("", { ...ctx, sessionManager: ephemeral });
    const ephemeralCopy = host.requests.at(-1).session;
    expect(dirname(ephemeralCopy)).toBe(ephemeralDir);
    expect(SessionManager.open(ephemeralCopy).buildSessionContext().messages).toEqual(ephemeral.buildSessionContext().messages);
    expect(ephemeral.getSessionFile()).toBeUndefined();
    expect(JSON.stringify(ephemeral.getEntries())).toBe(before);
  } finally {
    if (oldOwner === undefined) delete process.env.CODEX_SANDBOX_PI_OWNER; else process.env.CODEX_SANDBOX_PI_OWNER = oldOwner;
    if (oldAttachment === undefined) delete process.env.CODEX_SANDBOX_PI_ATTACHMENT; else process.env.CODEX_SANDBOX_PI_ATTACHMENT = oldAttachment;
    if (oldAgentDir === undefined) delete process.env.PI_CODING_AGENT_DIR; else process.env.PI_CODING_AGENT_DIR = oldAgentDir;
    await host.close();
    if (ephemeralDir) rmSync(ephemeralDir, { recursive: true, force: true });
    f.cleanup();
  }
});

test("socket EOF, malformed response, timeout and connection error terminate without replay", async () => {
  for (const mode of ["eof", "malformed", "timeout"]) {
    const f = fixture();
    const host = await controller(f.dir, (_request, socket) => {
      if (mode === "eof") socket.end();
      if (mode === "malformed") socket.end("not json\n");
    });
    try {
      const error = await requestOwner(host.path, { op: "side", attachment: "t", session: "snapshot" }, 30).catch(e => e);
      expect(error).toBeInstanceOf(Error);
      expect(error.snapshotMayBePublished).toBe(true);
      expect(host.requests.length).toBe(1);
    } finally { await host.close(); f.cleanup(); }
  }
  const error = await requestOwner("/nonexistent/pi-side-owner.sock", { op: "side", attachment: "t", session: "snapshot" }, 30).catch(e => e);
  expect(error).toBeInstanceOf(Error);
  expect(error.snapshotMayBePublished).toBe(false);
});

function restartExec(initial: any, fail = false) {
  let encoded = initial === undefined ? "" : Buffer.from(JSON.stringify(initial)).toString("base64url");
  const writes: any[] = [];
  return { writes, exec: async (_command: string, args: string[]) => {
    if (args[0] === "show-option") return { code: 0, stdout: encoded + "\n", stderr: "" };
    expect(args).toContain("-F");
    const format = args.at(-1)!;
    const match = /^#\{\?#\{==:#\{@codex_sandbox_restart\},([^,]+)\},([^,]+),#\{@codex_sandbox_restart\}\}$/.exec(format)!;
    expect(match).not.toBeNull();
    const updated = encoded === match[1] ? match[2] : encoded;
    writes.push(JSON.parse(Buffer.from(updated, "base64url").toString()));
    if (!fail) encoded = updated;
    return { code: fail ? 1 : 0, stdout: "", stderr: "" };
  } };
}

test("restart publication follows native SDK switching and custom storage without writing sessions", async () => {
  const f = fixture();
  const env = { TMUX: process.env.TMUX, TMUX_PANE: process.env.TMUX_PANE };
  try {
    process.env.TMUX = "fixture"; process.env.TMUX_PANE = "%7";
    const pi = restartExec({ version: 1, pane: "%7", repository: "/launcher/repo", session: "launch-id", token: "generation" });
    const source = SessionManager.create(f.dir, join(f.dir, "custom-storage"));
    const files = readdirSync(source.getSessionDir());
    await publishRestartSession(pi as any, source);
    expect(pi.writes[0]).toEqual({ version: 2, pane: "%7", repository: "/launcher/repo",
      session: source.getSessionFile(), cwd: f.dir, token: "generation" });
    expect(readdirSync(source.getSessionDir())).toEqual(files);
    const switched = SessionManager.create(f.dir, join(f.dir, "other-storage"));
    switched.appendMessage(assistant());
    source.setSessionFile(switched.getSessionFile());
    const before = readFileSync(switched.getSessionFile(), "utf8");
    await publishRestartSession(pi as any, source);
    expect(pi.writes[1].session).toBe(switched.getSessionFile());
    expect(readFileSync(switched.getSessionFile(), "utf8")).toBe(before);
    await publishRestartSession(pi as any, SessionManager.inMemory(f.dir));
    expect(pi.writes[2].session).toBeNull();
    expect(pi.writes[2].token).toBe("generation");
  } finally {
    for (const [key, value] of Object.entries(env)) {
      if (value === undefined) delete process.env[key]; else process.env[key] = value;
    }
    f.cleanup();
  }
});

test("missing/invalid restart metadata never writes and publication errors use readiness notification", async () => {
  const f = fixture();
  const keys = ["TMUX", "TMUX_PANE", "CODEX_SANDBOX_PI_OWNER", "CODEX_SANDBOX_PI_ATTACHMENT"];
  const env = keys.map(key => process.env[key]);
  const host = await controller(f.dir, (_request, socket) => socket.end('{"ok":true}\n'));
  try {
    process.env.TMUX = "fixture"; process.env.TMUX_PANE = "%7";
    const absent = restartExec(undefined);
    await publishRestartSession(absent as any, f.source);
    expect(absent.writes).toEqual([]);
    for (const invalid of [{ version: 3 }, { version: 1, pane: "%8", repository: "/repo", session: "id", token: "t" },
      { version: 2, pane: "%7", repository: "/repo", session: null, cwd: "relative", token: "t" }]) {
      const pi = restartExec(invalid);
      await expect(publishRestartSession(pi as any, f.source)).rejects.toThrow("Invalid");
      expect(pi.writes).toEqual([]);
    }
    const generation = { version: 1, pane: "%7", repository: "/repo", session: "id", token: "old" };
    let encoded = Buffer.from(JSON.stringify(generation)).toString("base64url");
    const replacement = Buffer.from(JSON.stringify({ ...generation, token: "replacement" })).toString("base64url");
    let writes = 0;
    await publishRestartSession({ exec: async (_command: string, args: string[]) => {
      if (args[0] === "show-option") return { code: 0, stdout: encoded };
      // Replacement lands at the publication command, not at a second read.
      encoded = replacement;
      const match = /^#\{\?#\{==:#\{@codex_sandbox_restart\},([^,]+)\},([^,]+),#\{@codex_sandbox_restart\}\}$/.exec(args.at(-1)!)!;
      expect(args).toContain("-F");
      expect(match).not.toBeNull();
      encoded = encoded === match[1] ? match[2] : encoded;
      writes++;
      return { code: 0, stdout: "" };
    } } as any, f.source);
    expect(writes).toBe(1);
    expect(encoded).toBe(replacement);
    await expect(publishRestartSession({ exec: async () => ({ code: 0, stdout: "not-json!" }) } as any,
      f.source)).rejects.toThrow("Invalid");
    delete process.env.TMUX;
    await publishRestartSession({ exec: () => { throw Error("unexpected exec"); } } as any, f.source);
    process.env.TMUX = "fixture"; delete process.env.TMUX_PANE;
    await publishRestartSession({ exec: () => { throw Error("unexpected exec"); } } as any, f.source);
    process.env.TMUX_PANE = "%7";
    process.env.CODEX_SANDBOX_PI_OWNER = host.path; process.env.CODEX_SANDBOX_PI_ATTACHMENT = "attachment";
    for (const pi of [restartExec({ version: 3 }), restartExec({ version: 1, pane: "%7", repository: "/repo", session: "id", token: "t" }, true)]) {
      let start: any;
      const errors: any[] = [];
      sessionSide({ ...pi, on: (_name: string, handler: any) => { start = handler; }, registerCommand: () => {} } as any);
      await start({}, { mode: "tui", sessionManager: f.source, ui: { notify: (...args: any[]) => errors.push(args) } });
      expect(errors).toHaveLength(1);
      expect(errors[0][0]).toContain("Host Pi readiness:");
      expect(errors[0][1]).toBe("error");
    }
  } finally {
    keys.forEach((key, i) => { if (env[i] === undefined) delete process.env[key]; else process.env[key] = env[i]; });
    await host.close(); f.cleanup();
  }
});
