#!/usr/bin/env python3
"""Generate compact C rule tables from the authoritative Python rule model."""

from __future__ import annotations

import argparse
from pathlib import Path

import hand_rules

TABLES = (
    ("initial", hand_rules.INITIAL_TOKENS),
    ("star_initial", hand_rules.STAR_INITIALS),
    ("vowel", hand_rules.VOWELS),
    ("final", hand_rules.FINAL_TOKENS),
    ("star_final", hand_rules.STAR_FINALS),
    ("prefix", hand_rules.PREFIXES),
    ("suffix", hand_rules.SUFFIXES),
    ("whole", hand_rules.WHOLE_STROKES),
)


def c_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"').replace("\0", "\\0")
    return '"' + escaped + '"'


def generate() -> str:
    strings: list[str] = []
    offsets: dict[str, int] = {}
    pool_size = 0

    def intern(value: str) -> int:
        nonlocal pool_size
        if value not in offsets:
            offsets[value] = pool_size
            strings.append(value)
            pool_size += len(value.encode("ascii")) + 1
        return offsets[value]

    entries: dict[str, list[tuple[int, int, int]]] = {}
    value_offsets: list[int] = []
    for table_name, table in TABLES:
        table_entries = []
        for key, values in table.items():
            first_value = len(value_offsets)
            value_offsets.extend(intern(value) for value in values)
            table_entries.append((intern(key), first_value, len(values)))
        entries[table_name] = table_entries

    lines = [
        "/* Generated by generate_c_rules.py; do not edit. */",
        "#pragma once",
        "",
        "typedef struct {",
        "    uint16_t key_offset;",
        "    uint16_t first_value;",
        "    uint8_t value_count;",
        "} lw_rule_entry_t;",
        "",
        "static const char lw_rule_strings[] =",
    ]
    for value in strings:
        lines.append(f"    {c_string(value + chr(0))}")
    lines.extend(("    ;", "", "static const uint16_t lw_rule_value_offsets[] = {"))
    for index in range(0, len(value_offsets), 12):
        lines.append("    " + ", ".join(str(value) for value in value_offsets[index:index + 12]) + ",")
    lines.extend(("};", ""))
    for table_name, _ in TABLES:
        lines.append(f"static const lw_rule_entry_t lw_{table_name}_rules[] = {{")
        for key_offset, first_value, value_count in entries[table_name]:
            lines.append(f"    {{{key_offset}, {first_value}, {value_count}}},")
        lines.extend(("};", f"#define LW_{table_name.upper()}_RULE_COUNT {len(entries[table_name])}u", ""))
    # The naturally aligned C entry is six bytes on the ARM target.
    lines.append(f"#define LW_RULE_SERIALIZED_BYTES {pool_size + len(value_offsets) * 2 + sum(len(v) * 6 for v in entries.values())}u")
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    args.output.write_text(generate())


if __name__ == "__main__":
    main()
