#!/bin/sh

exists () { command -v "$1" >/dev/null 2>&1; }

awawa_handler() {
	DOTFILES=$(dirname "$(dirname "$(realpath ~/.profile)")")
	{ if exists figlet; then figlet "$1!!!"; else echo "$1!!!"; fi
        } | cowsay -f "$DOTFILES"/lib/angel.cow -n
}

suggest_install() {
	# this looks weird because it uses absolute paths. we're the command-not-found handler, we don't want to call ourselves indefinitely.
	if [ -e /usr/lib/command-not-found ]
	then
		msg=$(/usr/lib/command-not-found -- "$1")
		echo "$msg" >&2
		printf "sudo "
		echo "$msg" | tail -n +2
		return 123
	elif PKGFILE=$(command -v pkgfile 2>/dev/null) \
		&& pkgs=$($PKGFILE --binaries -- "$1")
	then
		{
			echo "The program '$1' is not currently installed, but can be installed with:"
			for p in $pkgs; do
				echo "  pacman -S $p"
			done
		} >&2
		echo "sudo pacman -S --noconfirm $pkgs" | head -n1
		return 123
	elif BREW=$(command -v brew_which_formula 2>/dev/null) \
		&& pkgs=$($BREW -- "$1") \
		&& [ -n "$pkgs" ]
	then
		{
			echo "The program '$1' is not currently installed, but can be installed with:"
			for p in $pkgs; do
				echo "  brew install $p"
			done
		} >&2
		printf "env NONINTERACTIVE=1 brew install %s" "$(echo "$pkgs" | head -n1)"
		return 123
	elif [ -x /usr/libexec/pk-command-not-found ]
	then
		timeout .1 /usr/libexec/pk-command-not-found "$1" >&2
	else
		return 122
	fi
}

default_command_not_found() {
	printf "%s: command not found\n" "$1" >&2

	if [ -e /usr/libexec/pk-command-not-found ]; then
		echo "  consider searching for it with:"
		echo "  /usr/libexec/pk-command-not-found '$1'"
	fi

	return 127
}

command_not_found_handle() {
	# short-circuit if we're still starting up
	if [ -n "$RPS1" ]; then
		default_command_not_found "$@"
		return $?
	fi
	case "$1" in
		# awawawa!
		awa|awawa*) awawa_handler "$@"; return 0;;
		# check if we forgot to put a space between `g` and the git subcommand, but not for `gh`, which is its own command
		gh) ;;
		g*) sub=${1#*g}
		if git --list-cmds=list-mainporcelain,others,nohelpers,alias,config | grep "^$sub$" -q; then
			shift
			git "$sub" "$@"
			return $?
		fi;;
		# this is kinda cursed
		cc) ;;
		# lol, lmao
		cargo) ;;
		c) ;;
		c*) sub=${1#*c}
		if cargo --list | awk '{print $1}' | grep "^$sub$" -q; then
			shift
			cargo "$sub" "$@"
			return $?
		fi;;
	esac

	install_cmd=$(suggest_install "$@")
	if ! [ $? = 123 ]; then
		default_command_not_found "$@"
	elif [ -n "$install_cmd" ]; then
		printf 'Install and run it now with "%s && %s"? [y/N] ' "$install_cmd" "$*"
		read -r do_install
		case "$do_install" in
			y*) $install_cmd; exec "$@";;
			*) return 123;;
		esac
	fi
}

if ! [ $# = 0 ]; then
	command_not_found_handle "$@"
fi
