#!/bin/sh

set -e

. lib/lib.sh

if [ -n "$DOAS_USER" ]; then
	SUDO_USER=$DOAS_USER
fi

packages=
brew_packages=
here=$(realpath "$(dirname "$0")")
my_home=$(getent passwd "$SUDO_USER" | cut -d: -f6)

queue_install() {
	pkg="$1"
	if [ "$IS_DEB" = 1 ]; then
		:
	elif [ "$IS_RPM" = 1 ]; then
		case "$pkg" in
			libusb-1.0-0-dev) return;; # not sure what this was for anyway
			antidote|lua-language-server) return;;
			openjdk21) pkg=java-25-openjdk;;
			liburi-perl) pkg=perl-URI ;;
			manpages) pkg=man-pages ;;
			manpages-dev) return;;  # included with man-pages
			libssl-dev) pkg=openssl-devel ;;
			libpam-fscrypt) return;; # fedora doesn't use ext4, so we don't use fscrypt
			libterm-readline-gnu-perl) pkg=perl-Term-ReadLine-Gnu ;;
			python3-pylsp) pkg=python3-lsp-server ;;
			build-essential) pkg=@development-tools ;;
			*) ;;
		esac
	elif [ "$IS_BREW" = 1 ]; then
		case "$pkg" in
			build-essential|fscrypt|libpam-fscrypt|lib*-dev|lib*-perl|manpages*|xdg-utils|strace|valgrind) return;; # ¯\_(ツ)_/¯
			unzip|curl|clangd|python3-pip|traceroute) return;; # packaged by xcode-tools
			ninja-build) pkg=ninja;;
			python3-pylsp) pkg=python-lsp-server;;
			openjdk21) pkg=openjdk@21;;
			fd-find) pkg=fd;;
			*) ;;
		esac
		# TODO
	elif [ -n "$IS_ARCH" ]; then
		case "$pkg" in
			antidote|build-essential|manpages-dev|libpam-fscrypt) return;;
			# NOTE: -dev packages in Debian are just included by default in Arch packages
			libusb-1.0-0-dev) pkg=libusb;;
			libssl-dev) pkg=openssl;;
			liburi-perl) pkg=perl-uri;;
			libterm-readline-gnu-perl) pkg=perl-term-readline-gnu;;
			ninja-build) pkg=ninja;;
			clangd) pkg=clang;;
			fd-find) pkg=fd;;
			gh) pkg=github-cli;;
			manpages) pkg=man-pages;;
			openjdk21) pkg=jdk21-openjdk;;
			python3-pip) pkg=python-pip;;
			python3-pylsp) pkg=python-lsp-server;;
			*) ;;
		esac	
	elif [ "$IS_ALPINE" = 1 ]; then
		case "$pkg" in
			#gh) pkg=github-cli;;
			gh) return;;  # don't want creds on remote servers
			nvim) pkg=neovim;;
			fd-find) pkg=fd;;
			git-delta) pkg=delta;;
			kitty) pkg="$pkg kitty-kitten";;
			ninja-build) pkg="$pkg ninja-is-really-ninja";;
			liburi-perl) pkg=perl-uri ;;
			libterm-readline-gnu-perl) pkg=perl-term-readline-gnu ;;
			manpages) pkg=man-pages ;;
			antidote|bpytop|build-essential|clangd|cowsay|fscrypt|fzy|glow|libpam-fscrypt|libssl-dev|libusb-1.0-0-dev|lua-language-server|signal-desktop|manpages-dev|nvim|pkg-config|python3-pip|python3-pylsp|xdot) return;; # ¯\_(ツ)_/¯
			*) ;;
		esac
	elif [ "$IS_CHIMERA" = 1 ]; then
		case "$pkg" in
			antidote|asciinema|bpytop|build-essential|cowsay|direnv|fscrypt|gdu|gh|git-absorb|libpam-fscrypt|libusb-1.0-0-dev|manpages|manpages-dev|nmap|lua-language-server|libterm-readline-gnu-perl|rclone|shellcheck|tcsh|shfmt) return;;
			clangd) pkg=clang;;
			liburi-perl) pkg=perl-uri;;
			pkg-config) pkg=pkgconf;;
			python3-pip) pkg=python-pip;;
			python3-pylsp) pkg=python-lsp-server;;
			ninja-build) pkg=ninja;;
			nvim) pkg=neovim;;
			libssl-dev) pkg=openssl3-devel;;
			xdot) pkg=graphviz;;
			*) ;;
		esac
	fi
	packages="$packages $pkg"
}

should_copy_global() {
	local=$1
	DEST=$2

	if [ -e "$DEST" ] \
		&& ! grep "^# Generated by .*setup_sudo.sh" "$DEST" >/dev/null 2>&1
	then
		echo "error: $DEST already exists, refusing to overwrite"
		if [ "$local" = 1password.repo ]; then  # managed by 1pass package
			return 1
		fi
		exit 1
	fi

	printf "confirm: install ./global/$local to $DEST? [y/N] "
	read -r REPLY
	if ! [ "$REPLY" = y ]; then
		echo "ok, skipping"
		return 1
	fi
	return 0
}

copy_globals() {
	# can't use --dirty here or git will chown the index to root :/
	v="$(realpath "$0") v$(git describe --always)"
	d=$(date "+%F %T")
	for f in "$(realpath global)"/*; do
		base=$(basename "$f")
		if [ "$base" = 1password.repo ] && ! [ -n "$IS_RPM" ]; then continue; fi
		while IFS="=" read -r local DEST; do
			if [ "$local" = "$base" ]; then break; fi
		done < install/global.txt

		if ! [ "$1" = --force ] && ! should_copy_global "$local" "$DEST"; then continue; fi

		mkdir -p "$(dirname "$DEST")"
		{
			h="# Generated by $v from "./global/$local" at $d"
			if [ "$(head -c2 "$f")" = "#!" ]; then
				head -n1 "$f"
				echo "$h"
				tail -n+2 "$f" | sed "s/SETUP_HOSTNAME/$(hostname)/g"
			else
				echo "$h"
				cat "$f" | sed "s/SETUP_HOSTNAME/$(hostname)/g"
			fi
		} >"$DEST"
		chmod a+r "$DEST"
	done
}

# this script is very opinionated. you may not want to run everything here.

install_features () {
	if [ -n "$SUDO_USER" ] && ! exists keymapp; then
		if [ -n "$IS_DEB" ]; then
			usermod -aG plugdev "$SUDO_USER"
		fi
		t=$(download https://oryx.nyc3.cdn.digitaloceanspaces.com/keymapp/keymapp-latest.tar.gz)
		tar -xf "$t"
		chmod +x keymapp
		mkdir -p "$my_home/.local/bin"
		chown "$SUDO_USER:$SUDO_USER" "$my_home/.local/bin"
		mv keymapp "$(getent passwd "$SUDO_USER" | cut -d: -f6)"/.local/bin/keymapp
	fi

	if ! exists tailscale; then curl -fsSL https://tailscale.com/install.sh | sh; fi

	set +x
	echo "queueing packages to install"
	for pkg in $(grep -v '^\s*#' install/packages.txt | tr '\n' ' '); do
		queue_install "$pkg"
	done

	if is_wsl; then
		queue_install keychain
	fi

	set -x
	if [ -n "$IS_DEB" ]; then
		# thanks to https://github.com/zulip/zulip/pull/10911/files
		if ! apt-cache policy | grep -q "l=Ubuntu,c=universe"; then
			add-apt-repository universe
			apt-get update
		fi

		# https://learn.microsoft.com/en-us/powershell/scripting/install/install-ubuntu
		if ! exists pwsh; then
			# Download the Microsoft repository GPG keys
			wget -q "https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb"
			# Register the Microsoft repository GPG keys
			dpkg -i packages-microsoft-prod.deb
			# Install PowerShell
			queue_install powershell
		fi

		if ! exists code && ! is_wsl; then
			download https://go.microsoft.com/fwlink/?LinkID=760868 code.deb
			queue_install ./code.deb
		fi

		if [ "$(git --version | cut -d ' ' -f3 | cut -d. -f2)" -lt 35 ]; then
			# this often happens on WSL and borks because of zdiff3; install a newer version of git
			add-apt-repository ppa:git-core/ppa && queue_install git
		fi

		apt update
		apt install -y $packages
	elif [ -n "$IS_RPM" ]; then
		rpm --import https://downloads.1password.com/linux/keys/1password.asc
		queue_install 1password

		# https://rpmfusion.org/Configuration
		dnf install -y "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm" \
			"https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm"
		dnf install -y libavcodec-freeworld h264enc x264 x265 openh264 --allow-erasing

		dnf install -y $packages
	elif [ -n "$IS_ALPINE" ]; then
		# Use GNU less so Delta works properly
		apk add less py3-pip zsh $packages
	elif [ -n "$IS_ARCH" ]; then
		pacman --sync --refresh --sysupgrade --needed $packages
	elif [ -n "$IS_CHIMERA" ]; then
		apk add $packages
	elif [ -n "$IS_BREW" ]; then
		brew install -q $packages
	# SUSE
	#zypper addrepo https://cli.github.com/packages/rpm/gh-cli.repo
	#zypper ref
	#zypper install gh
	fi

	brew_packages="$brew_packages $(grep -v '^\s*#' install/brew_packages.txt | tr '\n' ' ')"
	if [ -n "$SUDO_USER" ]; then
		if ! exists brew; then
			sudo -u "$SUDO_USER" bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
			eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv sh)"
		fi
		sudo -u "$SUDO_USER" $(which brew) install -q $brew_packages
	else
		brew install -q $brew_packages
	fi
}

install_security () {
	if ! [ -n "$IS_DEB" ]; then
		return
	fi

	if ! dpkg -l unattended-upgrades >/dev/null; then
		apt-get update
		apt-get install -y unattended-upgrades
	fi
	unattended-upgrades || true
}

encrypt() {
	if fscrypt_supported; then
		encrypt_home_dir
	else
		setup_initramfs
	fi
}

fscrypt_supported() {
	if [ -z "$SUDO_USER" ]; then
		fail "don't know original user; giving up"
	fi

	fstype=$(df "$my_home" --output=fstype | tail -n1)
	[ "$fstype" = ext4 ]
}

encrypt_home_dir() {
 if fscrypt status "$my_home" | grep "encrypted with fscrypt">/dev/null; then
	 return;
 fi

	dev=$(df "$my_home" --output=source | tail -n1)

	if ! dumpe2fs -h "$dev" 2>/dev/null | grep -q 'Filesystem features:.*encrypt'; then
		tune2fs -O encrypt "$dev"
	fi

	fscrypt setup --all-users
	# can't be a link because we're about to encrypt the home drive
	cp "$DIR"/02-pam-unlock.sh /etc/profile.d
	if [ -e /etc/zshenv ]; then
		zenv=/etc/zshenv
	else
		zenv=/etc/zsh/zshenv
	fi
	echo ". /etc/profile" >> $zenv

	# this is the dangerous part
	backup=$(dirname $my_home)/$(basename $my_home).bak
	mv $my_home $backup
	mkdir $my_home
	chown $SUDO_USER:$SUDO_USER $my_home
	fscrypt encrypt --source=pam_passphrase --user=$SUDO_USER $my_home
	# we have to copy anyway to encrypt, may as well use cp instead of mv so we can confirm it's correct
	rsync -azAHX --info=progress2 $backup/ $my_home
	echo "setup encrypted home drive; delete backup? [y/N]" >/dev/tty
	if read -r; [ "$REPLY" = y ]; then
		echo "deleting" >&2
		rm -rf $backup
	else
		echo "retaining backup in $backup" >&2
	fi
}

setup_initramfs() {
	if ! exists dracut || ! [ -f /etc/dracut.conf ]; then
		fail "only know how to manage initramfs managed by dracut"
	fi
	if ! [ -e /usr/lib/dracut/modules.d/46dropbear ]; then
		echo 'kernel_cmdline=rd.neednet=1' >/etc/dracut.conf.d/network.conf
		ln -sf "$DIR/46dropbear" /usr/lib/dracut/modules.d
		dracut --force
	fi
}

remove_unwanted () {
	if [ -n "$IS_DEB" ]; then
		apt autoremove --purge apt-xapian-index
	elif [ -n "$IS_RPM" ]; then
		# this is strictly worse than zsh's builtin `which`, lmao
		rm /etc/profile.d/which2.sh
	fi
}

DIR="$(dirname "$(realpath "$0")")"
. "$DIR"/lib.sh
if exists dpkg; then
	IS_DEB=1
elif exists dnf; then
	IS_RPM=1
elif exists apk; then
	. /etc/os-release
	if [ "$ID" = chimera ]; then
		IS_CHIMERA=1
	else
		IS_ALPINE=1
	fi
elif exists pacman; then
	IS_ARCH=1
elif exists brew; then
	IS_BREW=1
else
	echo "$0: Unsupported distro"
	exit 1
fi

main() {
	copy_globals
	set -x
	install_security
	install_features

	if [ "$(uname)" = Darwin ]; then
		launchctl config user path "/usr/bin:/bin:/usr/sbin:/sbin:$(realpath "$here/../bin"):$(brew --prefix)/bin"
	fi

	remove_unwanted
	encrypt
	set +x
}

if [ $# = 0 ]; then
	echo "usage: $0 main"
	exit 1
fi

"$@"
