BASH_PROFILE_READ=1
if [ -z "${MY_GITHUB:-}" ]; then
   # these are set by the distro and break functions >:(
   unalias ls la ll l alert ip .. 2>/dev/null
	source ~/.profile || return
fi
shopt -s histappend
shopt -s checkwinsize
[ "$BASH_VERSINFO" -gt 3 ] && shopt -s globstar
shopt -s checkhash
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases || return
fi
case "$-" in
	*i*) ;;
	*) return;;
esac

## History ##
# don't put duplicate lines in the history.
HISTCONTROL=ignoredups

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=-1  # never delete
#############

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
   debian_chroot=$(cat /etc/debian_chroot)
fi

# enable programmable completion features
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion || return
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion || return
  fi
fi

# https://unix.stackexchange.com/questions/245331
.. () { cd ..; }
function @ { HEAD "$@"; }
rust-gdb () { command rust-gdb -q "$@"; }

# list directory after changing
cd () {
	builtin cd "$@" && status
}

# bash-specific keybinds
# note: put things in inputrc instead if possible
bind '" ":magic-space'
bind '"\C-@":shell-expand-line'

# completion
complete_alias() {
   local alias cmd spec quoted_alias
   # https://unix.stackexchange.com/questions/4219/how-do-i-get-bash-completion-for-command-aliases#comment1466732_570866
   alias="$1"
   cmd="$2"
   # if this command's completion doesn't live on disk (e.g. zoxide), __load_completion will fail,
   # even though `complete -p` succeeds.
   if exists __load_completion; then
      __load_completion "$cmd" || true
   fi
   if ! complete -p "$cmd" >/dev/null 2>&1; then
      echo "error: failed to load completion for $cmd" >&2
      return 1
   fi
   spec=$(complete -p "$cmd") || return
   printf -v quoted_alias %q "$alias"
   eval "${spec% *} $quoted_alias"
}
if exists cargo; then
   complete_alias c cargo || return
fi
if exists git; then
   complete_alias g git || return
fi
# jj has support for user-defined aliases. these can change between invocations, and even between
# one command ending and the other starting. refresh the completions between each invocation of jj.
if exists jj; then
   __jj_dynamic() {
      jj_completion=$(jj util completion bash) || return
      eval "$jj_completion" || return
      unset jj_completion
      _jj "$@"
      # `jj util completion` overrides our `complete` >:(
      complete -F __jj_dynamic -o nosort -o bashdefault -o default jj
   }
   complete -F __jj_dynamic -o nosort -o bashdefault -o default jj
fi
if exists zoxide; then
   zoxide_init=$(zoxide init bash) || return
   eval "$zoxide_init" || return
   unset zoxide_init
   cd() { z "$@" && status; }
   complete_alias cd z
fi

if [ -f ~/.local/bashrc ]; then
	source ~/.local/bashrc || return
fi

if [ -f ~/.local/lib/fzf-tab-completion/bash/fzf-bash-completion.sh ]; then
	source ~/.local/lib/fzf-tab-completion/bash/fzf-bash-completion.sh || return
	bind -x '"\t": fzf_bash_completion'
fi

if exists atuin; then
	atuin_init=$(atuin init bash --disable-up-arrow) || return
	eval "$atuin_init" || return
	unset atuin_init
fi
if exists direnv; then
	direnv_init=$(direnv hook bash) || return
	eval "$direnv_init" || return
	unset direnv_init
fi
