# debugging:
# to show what keypresses are mapped to:
#    hook global -always RawKey .* %{ echo -debug %val{hook_param} }
# to show currently set options: `:debug options` and then `:logs`
#	  or for a single option: `:echo %opt{aligntab}`
# to show possible format strings: `:doc expansions`
# to show possible options: `:doc options`
# for writing hooks: `:doc hooks`
# to show inferred filetypes: https://github.com/mawww/kakoune/blob/master/rc/detection/file.kak

add-highlighter global/ wrap
set-option global aligntab false
set-option global tabstop 2
hook global WinSetOption filetype=sh %{
    set-option buffer aligntab true
    set-option buffer formatcmd shfmt
}

# vim and helix mappings
map global normal D 'Gld'  # note: also deletes the current selection
map global normal , <space>  # shrink to single selection
map global normal = ':format<ret>'
# doesn't work because kak doesn't allow remapping C-c
# map global normal <c-c> ':comment-line<ret>'
# none of these work because kak doesn't receive the keypresses :(
# map global normal <c-/> ':comment-line<ret>'
# map global normal <c-_> ':comment-line<ret>'
alias global x write-quit
alias global buffer-close delete-buffer
alias global bc delete-buffer
alias global open edit
alias global o edit

# computer-touching bullshit
define-command edit-config "edit ~/.config/kak/kakrc" -docstring "edit user kakrc"
alias global ec edit-config
define-command logs "edit *debug*" -docstring "view *debug* logs"
alias global log logs

# copy to system clipboard using OSC 52 escape codes
hook global NormalKey y|d|c %{ nop %sh{
	printf "\033]52;c;$(printf "%s" "$kak_reg_dquote" | base64)\007" > /dev/tty
}}

# add some common features from helix
declare-user-mode picker
map global normal <space> ":enter-user-mode picker<ret>" -docstring "picker mode (helix emulator)"
map global picker f ':edit ' -docstring "file picker"
map global picker b ':buffer ' -docstring "buffer picker"
map global picker s ': lsp-document-symbol<ret>' -docstring "symbol picker"
map global picker d ': lsp-diagnostics<ret>' -docstring "workspace diagnostic picker"
map global picker r ': lsp-rename-prompt<ret>' -docstring "rename the selection"
map global picker c ': comment-line<ret>' -docstring "comment out the current line"
# map global picker a ': lsp-code-actions<ret>' -docstring "show LSP actions"
map global picker . ': lsp-code-actions<ret>' -docstring "show LSP actions"

# LSP
eval %sh{kak-lsp --kakoune -s $kak_session}  # Not needed if you load it with plug.kak.
lsp-enable

hook global WinSetOption filetype=.* %{
  hook window -group semantic-tokens BufReload .* lsp-semantic-tokens
  hook window -group semantic-tokens NormalIdle .* lsp-semantic-tokens
  hook window -group semantic-tokens InsertIdle .* lsp-semantic-tokens
  hook -once -always window WinSetOption filetype=.* %{
    remove-hooks window semantic-tokens
  }
}

