[tools]
node = "lts"
python = "latest"
rust = { version = "nightly", profile = "minimal", components = ["rustfmt", "clippy", "rust-analyzer", "miri"] }
uv = "latest"
"asdf:mise-plugins/mise-clojure" = "latest"
"aqua:cargo-bins/cargo-binstall" = "latest"
"github:clojure-lsp/clojure-lsp" = { version = "latest", filter_bins = "clojure-lsp" }
"aqua:antonmedv/fx" = "latest"
"aqua:LuaLS/lua-language-server" = "latest"
"aqua:mvdan/sh" = { version = "latest", filter_bins = "shfmt" }
"cargo:bacon" = { version = "latest", depends = ["rust", "aqua:cargo-bins/cargo-binstall"] }
"cargo:broot" = { version = "latest", depends = ["rust", "aqua:cargo-bins/cargo-binstall"] }
"cargo:cargo-audit" = { version = "latest", depends = ["rust", "aqua:cargo-bins/cargo-binstall"] }
"cargo:cargo-outdated" = { version = "latest", depends = ["rust", "aqua:cargo-bins/cargo-binstall"] }
"cargo:cargo-sweep" = { version = "latest", depends = ["rust", "aqua:cargo-bins/cargo-binstall"] }
"cargo:counts" = { version = "latest", depends = ["rust", "aqua:cargo-bins/cargo-binstall"] }
"cargo:librespot" = { version = "latest", depends = ["rust", "aqua:cargo-bins/cargo-binstall"], os = ["linux/x64", "macos/x64", "windows/x64"] }
"cargo:mdbook" = { version = "latest", depends = ["rust", "aqua:cargo-bins/cargo-binstall"] }
"aqua:Wilfred/difftastic" = "latest"
"aqua:Byron/dua-cli" = "latest"
"cargo:https://github.com/jj-vcs/jj" = { version = "rev:a0e7ebe7b037e822c506fcf6308055f8eecfb48a", crate = "jj-cli", bin = "jj", depends = ["rust"] }
"aqua:BurntSushi/ripgrep" = "latest"
"aqua:Myriad-Dreamin/tinymist" = "latest"
"github:glide-browser/glide" = { version = "latest", os = ["linux"], filter_bins = "glide" }
"aqua:pnpm/pnpm" = "latest"
"npm:perlnavigator-server" = { version = "latest", depends = ["node", "aqua:pnpm/pnpm"] }
"npm:bash-language-server" = { version = "latest", depends = ["node", "aqua:pnpm/pnpm"] }
"npm:typescript-language-server" = { version = "latest", depends = ["node", "aqua:pnpm/pnpm"] }
"npm:oxlint" = { version = "latest", depends = ["node", "aqua:pnpm/pnpm"] }
"npm:vscode-langservers-extracted" = { version = "latest", depends = ["node", "aqua:pnpm/pnpm"] }
"pipx:git-revise" = { version = "latest", depends = ["uv"] }
"pipx:pytest" = { version = "latest", depends = ["uv"], uvx_args = "--with pytest-xdist --with pytest-sugar --with pytest-instafail" }
"pipx:pylint" = { version = "latest", depends = ["uv"] }
"pipx:yt-dlp" = { version = "latest", depends = ["uv"] }

[settings]
lockfile = true
locked = true
npm.package_manager = "pnpm"
cargo.binstall = true
cargo.binstall_only = true

[settings.github]
oauth_client_id = "Iv23li0gR6P4iv8HXrsF"
oauth_export_env = "GITHUB_TOKEN"
use_git_credentials = true
