call plug#begin('~/.vim/plugged')
Plug 'mzlogin/vim-markdown-toc'
Plug 'csexton/trailertrash.vim'
Plug 'Chiel92/vim-autoformat'
Plug 'vim-latex/vim-latex'
Plug 'roxma/vim-paste-easy'
Plug 'tpope/vim-fugitive'
Plug 'airblade/vim-gitgutter'
Plug 'editorconfig/editorconfig-vim'
Plug 'aliou/bats.vim'
if has('nvim')
  source ~/.nvimrc
endif
call plug#end()

if !has('nvim')
  nmap <Enter> o<Esc>
  nmap <S-Enter> O<Esc>
endif
" allow forgetting to release shift
cmap Q q
cmap W w
nnoremap <C-f> :Autoformat<Enter>
nnoremap tt :TrailerTrim<Enter>
" https://superuser.com/a/1249453
nnoremap <C-i> i_<Esc>r
inoremap <S-Insert> <Esc>pi
" copy the current character until the 80th column (i.e. block comments)
nnoremap <C-b> y $80p079ld$

" o<pre><code>^M - insert '<pre><code>' on the next line
" </code></pre> - insert on the following line
" [^ - enter command mode
" ?<code>?1^M - go to the line following <code>, 2 lines after where the macro started
" :.,/<\/code>/-1 - on all lines from the current line to the line before </code>
" s/>/\>/g^M - substitue all occurrences of '>' with '>'
" ``k - go to the line before previous position of the cursor, 1 line after the macro started
" A^[[3~ - go to the end of the line and delete forwards
" use case: insert a code literal containing '>' in an html document
let @c='o<pre><code></code></pre>^P?<code>?1:.,/<\/code>/-1s/>/\&gt;/g``kA[3~'

" mostly copied from https://github.com/charlesdaniels/dotfiles/blob/master/provision/overlay/.vimrc
" Thanks, Charles!
set backspace=indent,eol,start " fix dumbass default backspace behavior
set nowrap                     " disable line wrapping
" enable a nice interactive menu for tab-completing buffers and such
set wildmenu
set wildmode=longest:full,full

syntax on
set number
set ignorecase "for searching"
set ruler
set ffs=unix
set mouse=a
" reduce pause after <Esc-O>
set ttimeoutlen=50

" highlighting
set hlsearch
hi Visual ctermbg=Yellow
hi Visual ctermfg=Black

if exists("+relativenumber")
	set relativenumber
endif

if has("clipboard")
    set clipboard=unnamedplus
endif

""""""""10""""""""20"""" text wrapping (gq) behaviour """"60""""""""70""""""""80

" configure indenting to work gqap correctly - not working quite right at the
" moment
if exists('+breakindent')  " breakindent was not merged until 2014
	set breakindent
else
	" a more primative and hacky solution - does not work as well as
	" breakindent
	set formatoptions=l
	set lbr
endif
set formatoptions+=q  " allow gqq to wrap comments

" disable hard wrapping
set wrap linebreak textwidth=0

""""""""10""""""""20""""""""3 shell configuration """"""""60""""""""70""""""""80

set shell=/bin/sh

if (has("win32") || has("win64"))
	set shell=C:\Windows\system32\cmd.exe
endif

""""""""10""""""""20""""""""30" UTF-8 handling "50""""""""60""""""""70""""""""80

if has("multi_byte") || has ("multi_byte_ime/dyn")
	" we can only enable utf-8 if we have multi byte support compiled in
	scriptencoding utf-8
	set encoding=utf-8
	set fileencoding=utf-8
	set fileencodings=ucs-bom,utf8,prc
	set langmenu=en_US.UTF-8
endif

" show non-printing characters

set list
set listchars=
set listchars+=trail:¬
set listchars+=precedes:«
set listchars+=extends:»
set listchars+=tab:>-


""""""""10""""""""20"""""""" indentation settings """"""""60""""""""70""""""""80

function TwoSpacesSoftTabs()
	set tabstop=2
	set shiftwidth=2
	set softtabstop=2
	set expandtab
endfunction

function EightSpacesHardTabs()
	set tabstop=8
	set shiftwidth=8
	set softtabstop=8
	set noexpandtab
endfunction

function EightSpacesSoftTabs()
	set tabstop=8
	set shiftwidth=4
	set softtabstop=8
	set expandtab
endfunction

function FourSpacesSoftTabs()
	set tabstop=4
	set shiftwidth=4
	set softtabstop=4
	set expandtab
endfunction

function FourSpacesHardTabs()
	set tabstop=4
	set shiftwidth=4
	set softtabstop=4
	set noexpandtab
endfunction

function CompileTex()
    w
    silent !pdflatex %
    redraw!
endfunction
inoremap <C-l> <Esc>:call CompileTex()<Enter>i
nnoremap <C-l> :call CompileTex()<Enter>

" use 2 spaces by default
call TwoSpacesSoftTabs()


""""""""10""""""""20""""""" filetype configuration """""""60""""""""70""""""""80

" forcibly use the c filetype for all header files
autocmd BufNewFile,BufRead *.h,*.c,*.cc,*.cpp,*.C,*.ino set filetype=c

" use tex filetype for *.tex
autocmd BufNewFile,BufRead *.tex,*.sty set filetype=tex

" Handle YAML files correctly
autocmd BufNewFile,BufRead *.yml,*.yaml,Sakefile set filetype=yaml

" fix broken behaviour for CHANGELOG files
autocmd BufEnter CHANGELOG setlocal filetype=text

" set up tab & space behaviour sensibly
autocmd FileType c call TwoSpacesSoftTabs()
autocmd FileType java call TwoSpacesSoftTabs()
autocmd FileType python call FourSpacesSoftTabs()
autocmd FileType tex call FourSpacesSoftTabs()
autocmd FileType yaml call FourSpacesSoftTabs()
autocmd FileType sh call FourSpacesHardTabs()
autocmd FileType perl call EightSpacesHardTabs()
autocmd FileType html call TwoSpacesSoftTabs()
autocmd FileType haskell call TwoSpacesSoftTabs()
autocmd FileType scheme call TwoSpacesSoftTabs()

if has("spell")
	" enable spell checking
	set spell spelllang=en_us
	set complete+=kspell " allow words as completions
	highlight clear SpellBad
	highlight clear SpellCap
	highlight clear SpellRare
	highlight clear SpellLocal
	highlight SpellBad cterm=underline gui=underline
	highlight SpellLocal cterm=underline gui=underline
endif

unmap <TAB>
set viminfo+=n/~.vim/viminfo
