# Set "$0" to zsh, not .profile
emulate sh
# Perform command substitution when evaluating prompt
setopt PROMPT_SUBST
# Set up the prompt
. ~/.profile
emulate zsh

alias help=run-help
alias -g stauts=status
alias -g serach=search

pure_shell() {
   env -u HISTFILE PS1='; ' zsh --no-rcs --no-globalrcs
}

autoload -Uz promptinit
promptinit
PROMPT="$PS1"

setopt histignorealldups sharehistory correct
# append immediately, not on close
setopt incappendhistory
# allow `cd ..`
setopt autocd

# save command in buffer before executing
bindkey "^Q" push-line
bindkey "^G" get-line

# emacs line editing
bindkey -e
# Alt + Right
bindkey ";3C" forward-word
# Alt + Left
bindkey ";3D" backward-word
# ctrl+left
bindkey ";5D" backward-word
# kitty passes \e[ but gnome-terminal doesn't :(
bindkey "\e[1;5D" backward-word
# ctrl+right
bindkey ";5C" forward-word
bindkey "\e[1;5C" forward-word

# by analogy with ^H
# this overrides clear-screen, but i don't care about clear-screen
bindkey "^L" forward-word

# properly bind Home, End, Delete (had trouble with this at one point)
# note: MUST come after 'bindkey -e'
bindkey "\e[H" beginning-of-line
bindkey "\e[F" end-of-line
bindkey "\e[3~" delete-char
# tmux gets these as different scancodes apparently?
bindkey "\e[1~" beginning-of-line
bindkey "\e[4~" end-of-line
# ctrl+del
bindkey "5~" delete-word
bindkey "\e[3;5~" delete-word # tmux
# alt+del
bindkey "3~" backward-delete-word
# ctrl+backspace
bindkey '^H' backward-delete-word

# space expands !... history
# TODO: see if we can make this more useful?
bindkey ' ' magic-space

# Keep 1000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=1000
SAVEHIST=10000000
HISTFILE=~/.zsh_history

# Use modern completion system
autoload -Uz compinit
compinit

# shift-tab cycles backwards through choices
bindkey '^[[Z' reverse-menu-complete

zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu select=2
if exists dircolors; then
  eval "$(dircolors -b)"
fi
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' menu select=long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true

zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'
zstyle ':completion:*' rehash true

COMPLETION=/usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
if [ -e "$COMPLETION" ]; then
	. "$COMPLETION"
fi

. $(dirname $(realpath ~/.profile))/../lib/antigen.zsh
antigen bundle zsh-users/zsh-autosuggestions
antigen apply

if exists jj; then source <(jj util completion zsh); fi
if exists zoxide; then
   source <(zoxide init zsh)
   # zoxide is annoying and makes `z` an alias instead of a function
   cd() { __zoxide_z "$@" && status; }
fi

eval "$(atuin init zsh --disable-up-arrow)"
