#!/bin/sh

set -u

if [ "$#" -lt 3 ] || [ "$2" != "--" ]; then
	printf '%s\n' 'usage: host-editor-pane STATUS -- EDITOR [ARG ...]' >&2
	exit 2
fi

status=$1
shift 2

"$@"
result=$?
printf '%s\n' "$result" > "$status" || exit
exit "$result"
