"""Keep the native Glide package out of mise's active tool set."""

import os
from pathlib import Path


GLIDE_TOOL = "github:glide-browser/glide"
NATIVE_EXECUTABLE = Path("/usr/bin/glide-bin")
MANAGED_CONFIG = (
    '# Generated by dotfiles libexec/setup/glide.py.\n'
    '[settings]\n'
    f'disable_tools = ["{GLIDE_TOOL}"]\n'
)


def configure_mise() -> str:
    config_home = Path(os.environ.get("XDG_CONFIG_HOME", Path.home() / ".config"))
    destination = config_home / "mise/conf.d/dotfiles-glide.toml"
    if destination.exists() and destination.read_text() != MANAGED_CONFIG:
        raise RuntimeError(f"refusing to overwrite unmanaged configuration: {destination}")
    if os.access(NATIVE_EXECUTABLE, os.X_OK):
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(MANAGED_CONFIG)
        return GLIDE_TOOL
    destination.unlink(missing_ok=True)
    return ""


if __name__ == "__main__":
    print(configure_mise())
