#!/bin/sh

set -e

. lib/shell/lib.sh

if [ -n "$DOAS_USER" ]; then
	SUDO_USER=$DOAS_USER
fi

here=$(realpath "$(dirname "$0")")
my_home=
if [ -n "${SUDO_USER:-}" ]; then
	if exists getent; then
		my_home=$(getent passwd "$SUDO_USER" | cut -d: -f6)
	elif is_macos; then
		my_home=$(dscl . -read "/Users/$SUDO_USER" NFSHomeDirectory | awk '{print $2}')
	else
		fail "cannot find the home directory for $SUDO_USER"
	fi
fi

should_copy_global() {
	local=$1
	DEST=$2

	if [ -e "$DEST" ] \
		&& ! grep "^# Generated by .*setup_sudo.sh" "$DEST" >/dev/null 2>&1
	then
		echo "error: $DEST already exists, refusing to overwrite"
		exit 1
	fi

	printf "confirm: install ./global/$local to $DEST? [y/N] "
	read -r REPLY
	if ! [ "$REPLY" = y ]; then
		echo "ok, skipping"
		return 1
	fi
	return 0
}

copy_globals() {
	# can't use --dirty here or git will chown the index to root :/
	v="$(realpath "$0") v$(git describe --always)"
	d=$(date "+%F %T")
	for f in "$(realpath global)"/*; do
		base=$(basename "$f")
		while IFS="=" read -r local DEST; do
			if [ "$local" = "$base" ]; then break; fi
		done < install/global.txt

		if ! [ "$1" = --force ] && ! should_copy_global "$local" "$DEST"; then continue; fi

		mkdir -p "$(dirname "$DEST")"
		{
			h="# Generated by $v from "./global/$local" at $d"
			shebang="$(head -c2 "$f")"
			#% for PAM
			if [ "$shebang" = "#!" ] || [ "$shebang" = "#%" ]; then
				head -n1 "$f"
				echo "$h"
				tail -n+2 "$f" | sed "s/SETUP_HOSTNAME/$(hostname)/g"
			else
				echo "$h"
				cat "$f" | sed "s/SETUP_HOSTNAME/$(hostname)/g"
			fi
		} >"$DEST"
		chmod a+r "$DEST"
	done
}

# this script is very opinionated. you may not want to run everything here.

install_device () {
	if [ -n "$SUDO_USER" ] && ! exists keymapp; then
		if [ -n "$IS_DEB" ]; then
			usermod -aG plugdev "$SUDO_USER"
		fi
		mkdir -p "$my_home/.local/bin"
		chown "$SUDO_USER:$SUDO_USER" "$my_home/.local/bin"
		t=$(download https://oryx.nyc3.cdn.digitaloceanspaces.com/keymapp/keymapp-latest.tar.gz)
		tar -xf "$t" -C "$my_home/.local/bin" keymapp
		chmod +x "$my_home/.local/bin/keymapp"
	fi
}

install_security () {
	if ! [ -n "$IS_DEB" ]; then
		return
	fi

	if ! dpkg -l unattended-upgrades >/dev/null; then
		apt-get update
		apt-get install -y unattended-upgrades
	fi
	unattended-upgrades || true
}

encrypt() {
	if fscrypt_supported; then
		encrypt_home_dir
	else
		setup_initramfs
	fi
}

fscrypt_supported() {
	if [ -z "$SUDO_USER" ]; then
		fail "don't know original user; giving up"
	fi

	fstype=$(df "$my_home" --output=fstype | tail -n1)
	[ "$fstype" = ext4 ]
}

encrypt_home_dir() {
 if fscrypt status "$my_home" | grep "encrypted with fscrypt">/dev/null; then
	 return;
 fi

	dev=$(df "$my_home" --output=source | tail -n1)

	if ! dumpe2fs -h "$dev" 2>/dev/null | grep -q 'Filesystem features:.*encrypt'; then
		tune2fs -O encrypt "$dev"
	fi

	fscrypt setup --all-users
	# can't be a link because we're about to encrypt the home drive
	cp "$DIR"/../../lib/02-pam-unlock.sh /etc/profile.d
	if [ -e /etc/zshenv ]; then
		zenv=/etc/zshenv
	else
		zenv=/etc/zsh/zshenv
	fi
	echo ". /etc/profile" >> $zenv

	# this is the dangerous part
	backup=$(dirname $my_home)/$(basename $my_home).bak
	mv $my_home $backup
	mkdir $my_home
	chown $SUDO_USER:$SUDO_USER $my_home
	fscrypt encrypt --source=pam_passphrase --user=$SUDO_USER $my_home
	# we have to copy anyway to encrypt, may as well use cp instead of mv so we can confirm it's correct
	rsync -azAHX --info=progress2 $backup/ $my_home
	echo "setup encrypted home drive; delete backup? [y/N]" >/dev/tty
	if read -r; [ "$REPLY" = y ]; then
		echo "deleting" >&2
		rm -rf $backup
	else
		echo "retaining backup in $backup" >&2
	fi
}

setup_initramfs() {
	if ! exists dracut || ! [ -f /etc/dracut.conf ]; then
		fail "only know how to manage initramfs managed by dracut"
	fi
	if ! [ -e /usr/lib/dracut/modules.d/46dropbear ]; then
		echo 'kernel_cmdline=rd.neednet=1' >/etc/dracut.conf.d/network.conf
		ln -sf "$DIR/../../lib/46dropbear" /usr/lib/dracut/modules.d
		dracut --force
	fi
}

remove_unwanted () {
	if [ -n "$IS_DEB" ]; then
		apt autoremove --purge apt-xapian-index
	elif [ -n "$IS_RPM" ]; then
		# this is strictly worse than zsh's builtin `which`, lmao
		rm /etc/profile.d/which2.sh
	fi
}

DIR="$(dirname "$(realpath "$0")")"
. "$DIR"/../../lib/shell/lib.sh
if exists dpkg; then
	IS_DEB=1
elif exists dnf; then
	IS_RPM=1
elif exists apk; then
	:
elif exists pacman; then
	:
elif exists brew; then
	:
else
	echo "$0: Unsupported distro"
	exit 1
fi

main() {
	set -x
	install_security
	install_device
	set +x
	copy_globals
	set -x

	if [ "$(uname)" = Darwin ]; then
		launchctl config user path "/usr/bin:/bin:/usr/sbin:/sbin:$(realpath "$here/../bin"):$(brew --prefix)/bin"
	fi

	remove_unwanted
	if [ -n "${SUDO_USER:-}" ]; then
		encrypt
	fi
	set +x
}

if [ $# = 0 ]; then
	echo "usage: $0 main"
	exit 1
fi

"$@"
