#!/bin/sh
set -eu

jj diff --git "$@" | awk '
  /^\+\+\+ / {
    patch_file = $0 ~ /\.(diff|patch)"?$/
    next
  }
  patch_file && $0 == "+ " { next }
  /^\+/ && /[[:blank:]]+$/ {
    print
    found = 1
  }
  END { exit found ? 1 : 0 }
'
