[user]
name = "jyn"
email = "github@jyn.dev"

[ui]
paginate = "never"
editor = ["/trusted/bin/jj-proxy", "reject-editor"]
diff-editor = ":builtin"
merge-editor = ":builtin"

[signing]
behavior = "drop"

[merge-tools.agent-split]
program = "/trusted/bin/agent-split-editor"
edit-args = ["$left", "$right"]

[aliases]
