import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import agentRoom from "./agent-room.ts";
import askUser from "./ask-user.ts";
import contextBreakdown from "./context-breakdown.ts";
import currentDate from "./current-date.ts";
import footer from "./footer.ts";
import hostOS from "./host-os.ts";
import skillReferenceAutocomplete from "./skill-reference-autocomplete.ts";
import instructionIncludes from "./pi-instruction-includes.ts";
import lunaCompaction from "./luna-compaction.ts";
import notifyWhenSettled from "./pi-notify.ts";
import promptHistorySearch from "./prompt-history-search.ts";
import runtimeIdentity from "./runtime-identity.ts";
import sessionTitle from "./session-title.ts";
import sessionHandoff from "./session-handoff.ts";
import sessionSide from "./session-side.ts";
import subagentRouting from "./subagent-routing.ts";
import systemPrompt from "./system-prompt.ts";
import subscriptionUsage from "./subscription-usage.ts";
import taskDirectedDocs from "./task-directed-docs.ts";
import validateSkill from "./validate-skill.ts";
import webSearch from "./pi-web-search.ts";

export default function dotfilesExtensions(pi: ExtensionAPI) {
  agentRoom(pi);
  askUser(pi);
  contextBreakdown(pi);
  currentDate(pi);
  footer(pi);
  hostOS(pi);
  skillReferenceAutocomplete(pi);
  lunaCompaction(pi);
  notifyWhenSettled(pi);
  instructionIncludes(pi);
  promptHistorySearch(pi);
  runtimeIdentity(pi);
  sessionTitle(pi);
  sessionHandoff(pi);
  sessionSide(pi);
  subagentRouting(pi);
  systemPrompt(pi);
  subscriptionUsage(pi);
  taskDirectedDocs(pi);
  validateSkill(pi);
  webSearch(pi);
}
