name: Linux setup tests

on:
  push:
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - alpine:latest
          - fedora:latest
          - archlinux:latest
          - ubuntu:26.04
    steps:
      - uses: actions/checkout@v4
      - name: Test setup
        env:
          CONTAINER_ENGINE: docker
        run: dev/setup/container-test "${{ matrix.image }}"

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install test runners
        run: brew install babashka uv
      - name: Test setup
        run: dev/test
